### ISSUE TITLE
setuptools >= 38.6.0 in `setup_requires` ?

### ISSUE THREAD

**Issue by johnyf** [di/markdown-description-example#2]
Following the [documentation](https://dustingram.com/articles/2018/03/16/markdown-descriptions-on-pypi), it may be useful to add a [`setup_requires=['setuptools>=38.6.0']`](https://github.com/pypa/setuptools/blob/master/CHANGES.rst#v3860), in case some developers find it relevant.

Of course, it is not a requirement that will prevent installation or upload to PyPI, only rendering. So it could go to a `requirements.txt`.

Also, `'twine>=1.11.0'` could be mentioned in a `dev_requirements.txt`.

**Comment by di** [comment]
Thanks, great suggestion! I've added this in 2574f80104a7581dcebe4ddb1c7fa18dc4b55a21.

I'm hesitant to add an extra file to this project, so I think for now it's OK that the twine requirement is not specified here (because it's specified in all the guides pointing to this project).

Thanks again!

**Comment by johnyf** [comment]
Thanks for making this addition!

**Comment by asottile** [comment]
`setup_requires` is too late as the `setup()` call has already happened before `setup_requires` is even processed:

```
$ pip install 'setuptools<36'
Collecting setuptools<36
  Downloading https://files.pythonhosted.org/packages/27/45/79618f80704497f74f2de1ca62216a5c3ffdbd49f43047c81c30e126a055/setuptools-35.0.2-py2.py3-none-any.whl (390kB)
    100% |████████████████████████████████| 399kB 3.7MB/s 
Collecting six>=1.6.0 (from setuptools<36)
  Using cached https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Collecting appdirs>=1.4.0 (from setuptools<36)
  Using cached https://files.pythonhosted.org/packages/56/eb/810e700ed1349edde4cbdc1b2a21e28cdf115f9faf263f6bbf8447c1abf3/appdirs-1.4.3-py2.py3-none-any.whl
Collecting packaging>=16.8 (from setuptools<36)
  Downloading https://files.pythonhosted.org/packages/ad/c2/b500ea05d5f9f361a562f089fc91f77ed3b4783e13a08a3daf82069b1224/packaging-17.1-py2.py3-none-any.whl
Collecting pyparsing>=2.0.2 (from packaging>=16.8->setuptools<36)
  Downloading https://files.pythonhosted.org/packages/6a/8a/718fd7d3458f9fab8e67186b00abdd345b639976bc7fb3ae722e1b026a50/pyparsing-2.2.0-py2.py3-none-any.whl (56kB)
    100% |████████████████████████████████| 61kB 1.9MB/s 
Installing collected packages: six, appdirs, pyparsing, packaging, setuptools
  Found existing installation: setuptools 39.2.0
    Uninstalling setuptools-39.2.0:
      Successfully uninstalled setuptools-39.2.0
Successfully installed appdirs-1.4.3 packaging-17.1 pyparsing-2.2.0 setuptools-35.0.2 six-1.11.0

$ python setup.py sdist
/usr/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
  warnings.warn(msg)
/usr/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'project_urls'
  warnings.warn(msg)

Installed /tmp/markdown-description-example/.eggs/setuptools-39.2.0-py3.6.egg
/usr/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
  warnings.warn(msg)
running sdist
running egg_info
creating markdown_description_example.egg-info
writing markdown_description_example.egg-info/PKG-INFO
writing dependency_links to markdown_description_example.egg-info/dependency_links.txt
writing top-level names to markdown_description_example.egg-info/top_level.txt
writing manifest file 'markdown_description_example.egg-info/SOURCES.txt'
reading manifest file 'markdown_description_example.egg-info/SOURCES.txt'
writing manifest file 'markdown_description_example.egg-info/SOURCES.txt'
warning: sdist: standard file not found: should have one of README, README.rst, README.txt

running check
creating markdown-description-example-0.0.1
creating markdown-description-example-0.0.1/markdown_description_example.egg-info
copying files to markdown-description-example-0.0.1...
copying setup.py -> markdown-description-example-0.0.1
copying markdown_description_example.egg-info/PKG-INFO -> markdown-description-example-0.0.1/markdown_description_example.egg-info
copying markdown_description_example.egg-info/SOURCES.txt -> markdown-description-example-0.0.1/markdown_description_example.egg-info
copying markdown_description_example.egg-info/dependency_links.txt -> markdown-description-example-0.0.1/markdown_description_example.egg-info
copying markdown_description_example.egg-info/top_level.txt -> markdown-description-example-0.0.1/markdown_description_example.egg-info
Writing markdown-description-example-0.0.1/setup.cfg
creating dist
Creating tar archive
removing 'markdown-description-example-0.0.1' (and everything under it)

$ cd dist/

$ pip wheel *.tar.gz
Processing ./markdown-description-example-0.0.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-b8xx1vr1/setup.py", line 3, in <module>
        with open('README.md') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'README.md'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-b8xx1vr1/

$ ls -al ../.eggs/
total 1004
drwxrwxr-x 2 asottile asottile    4096 Jun  1 17:59 .
drwxrwxr-x 6 asottile asottile    4096 Jun  1 17:59 ..
-rw-rw-r-- 1 asottile asottile     211 Jun  1 17:59 README.txt
-rw-rw-r-- 1 asottile asottile 1012041 Jun  1 17:59 setuptools-39.2.0-py3.6.egg
```

imo this is unnecessary boilerplate that _at best_ causes an unnecessary download of an `.egg` and produces a broken source distribution.  in reality, a runtime assertion would be better (for example a module-scoped assertion that checks `setuptools.__version__`)

**Comment by di** [comment]
@asottile Great catch. It didn't occur to me that [`setuptools` is unable to upgrade itself via `setup_requires`](https://github.com/pypa/setuptools/issues/1218#issuecomment-348296931). I've removed the commit.
